name: crediahorro
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  http: ^1.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.0
  jwt_decoder: ^2.0.1
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/default_avatar.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"